### ISSUE TITLE
don't write to bash, use an external script to load all the files

### ISSUE THREAD

**Issue by joergi** [joergi/superexport#1]
```bash
if [ ! -f $superexportfolder/.secretreader.sh ]; then
 echo "#!/bin/bash" > $superexportfolder/.secretreader.sh
 chmod +x $superexportfolder/.secretreader.sh
fi

echo -e $secretreader >> ~/.bashrc

```
this was changed in [this commit](https://github.com/joergi/superexport/commit/4f3c36ea1122398448bd9e838a47c12f75f24e99) , so it's now writing to the `.bashrc`

Unfortunately, with adding this to the `.bashrc`
```bash

also add the `.secretreader.sh` to your `.bashrc`  
```bash
source /home/$USERNAME/.superexport/.secretreader.sh
```
was not working... find out why and how to fix it

**Comment by jshiell** [comment]
Hmm, odd. We do the same thing in `snsh` and it works correctly. I don't think there's anything special there 🤔 

https://github.com/springernature/snsh/blob/main/bash_profile

EDIT: only thing I've spotted is we're using `.bash_profile` there rather than `.bashrc`.

**Comment by joergi** [comment]
thx, I will have a look

**Comment by joergi** [comment]
interesting...  I re-implemented, everything I removed, now it works.
not sure what I made wrong at this time...
thanks @jshiell  for hinting me, that it should work ;-)
